const SUPABASE_URL = 'https://apykziojynimjarwdwoe.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFweWt6aW9qeW5pbWphcndkd29lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI3MTA4MzcsImV4cCI6MjA5ODI4NjgzN30.g3NzSf94bLe__CJM8DZHPhYilsod2XtnasP5Di2iIHw';
const useSupabase = SUPABASE_URL.startsWith('http') && SUPABASE_ANON_KEY.length > 40;
const db = useSupabase ? window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
const $ = id => document.getElementById(id);
const tables = ['condominios','moradores','portaria','lancamentos','mensagens','avisos'];
let state = {condominios:[],moradores:[],portaria:[],lancamentos:[],mensagens:[],avisos:[],admin:null,morador:null,portariaUser:null,conversa:null,slide:0};
const uid = () => crypto.randomUUID ? crypto.randomUUID() : String(Date.now()+Math.random());
const today = () => new Date().toISOString().slice(0,10);
const money = v => Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc = v => String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(msg){const t=$('toast'); if(!t) return; t.textContent=msg; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),2600)}
function parseJson(v,d=[]){try{return typeof v==='string'?JSON.parse(v||'[]'):(v||d)}catch{return d}}
function condName(id){return state.condominios.find(c=>c.id===id)?.nome||'-'}
function localLoad(){tables.forEach(t=>state[t]=JSON.parse(localStorage.getItem('arq_'+t)||'[]')); if(!state.condominios.length){state.condominios=[{id:uid(),nome:'Condomínio Reserva das Praias',endereco:'Manaus/AM',responsavel:'Síndico'}]; localSaveAll();}}
function localSave(t){localStorage.setItem('arq_'+t,JSON.stringify(state[t]))} function localSaveAll(){tables.forEach(localSave)}
async function loadAll(){ if(useSupabase){for(const t of tables){const {data,error}=await db.from(t).select('*').order('created_at',{ascending:false}); if(!error) state[t]=data||[]; else if(t==='avisos') state[t]=[];}} else localLoad(); renderAll(); }
async function upsert(t,obj){obj.id=obj.id||uid(); obj.updated_at=new Date().toISOString(); if(useSupabase){const {error}=await db.from(t).upsert(obj); if(error){toast(error.message); return false;}} else {const i=state[t].findIndex(x=>x.id===obj.id); i>=0?state[t][i]=obj:state[t].unshift(obj); localSave(t);} await loadAll(); return true;}
async function removeRow(t,id){if(!id||!confirm('Confirmar remoção?'))return; if(useSupabase){const {error}=await db.from(t).delete().eq('id',id); if(error)return toast(error.message);}else{state[t]=state[t].filter(x=>x.id!==id); localSave(t);} await loadAll(); toast('Removido com sucesso.');}
async function fileToData(file){return new Promise((res,rej)=>{if(!file)return res(''); const r=new FileReader(); r.onload=()=>res(r.result); r.onerror=rej; r.readAsDataURL(file);});}
async function filesToData(input){return Promise.all([...((input&&input.files)||[])].map(async f=>({name:f.name,type:f.type,data:await fileToData(f)})));}
function optCond(sel,first='Selecione o condomínio'){if(!sel)return; const v=sel.value; sel.innerHTML=`<option value="">${first}</option>`+state.condominios.map(c=>`<option value="${c.id}">${esc(c.nome)}</option>`).join(''); sel.value=v;}
function optMor(sel,first='Selecione um morador'){if(!sel)return; const v=sel.value; sel.innerHTML=`<option value="">${first}</option>`+state.moradores.map(m=>`<option value="${m.id}">${esc(m.nome)} - ${esc(m.email)}</option>`).join(''); sel.value=v;}
function optLanc(sel){if(!sel)return; const v=sel.value; sel.innerHTML='<option value="">Selecione o lançamento</option>'+state.lancamentos.map(l=>`<option value="${l.id}">${esc(l.titulo)} - ${money(l.valor)}</option>`).join(''); sel.value=v;}
function table(head,rows){if(!rows.length)return '<p>Nenhum registro encontrado.</p>'; return `<table class="data-table"><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c??''}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function show(view){['loginArea','adminPanel','moradorPanel','portariaPanel'].forEach(id=>$(id)?.classList.add('hidden')); $(view)?.classList.remove('hidden'); window.scrollTo(0,0)}
function setBadge(id,n){const b=$(id); if(!b)return; b.textContent=n; b.classList.toggle('hidden',!n)}
function renderAll(){['moradorLoginCondominio','portariaLoginCondominio','moradorCondominio','portariaCondominio','lancamentoCondominio','avisoCondominio','msgFiltroCondominio','portariaFiltroCond','portariaMsgCond'].forEach(id=>optCond($(id),id.includes('Filtro')?'Todos os condomínios':'Selecione o condomínio')); optMor($('senhaMoradorSelect')); optMor($('removeMoradorSelect')); optLanc($('removeLancamentoSelect')); renderConds();renderMoradores();renderPortaria();renderLancamentos();renderAvisosAdmin();renderConversasAdmin();renderBadges(); if(state.morador)renderMoradorPanel(); if(state.portariaUser)renderPortariaPanel();}
function renderConds(){if($('condominiosList')) $('condominiosList').innerHTML=table(['Nome','Endereço','CNPJ','Responsável','Ações'],state.condominios.map(c=>[esc(c.nome),esc(c.endereco),esc(c.cnpj),esc(c.responsavel),actions('cond',c.id)]));}
function actions(t,id){return `<div class="row-actions"><button class="mini-btn" onclick="editItem('${t}','${id}')">Editar</button><button class="mini-btn danger" onclick="deleteItem('${t}','${id}')">Remover</button></div>`}
function pessoasHtml(m){const ps=parseJson(m.pessoas_vinculadas,[]); return ps.length?`<button class="mini-btn" onclick="showPessoas('${m.id}')">Exibir nomes vinculados</button>`:'-'}
function placaThumb(m){const img=m.foto_placa_data||m.foto_placa_url; return img?`<span class="plate-hover"><img src="${img}" class="plate-thumb"><span class="plate-preview"><img src="${img}"></span></span>`:''}
function renderMoradores(){if(!$('moradoresList'))return; $('moradoresList').innerHTML=table(['Nome','E-mail','CPF','Celular','Unidade','Veículo','Pessoas vinculadas','Condomínio','Ações'],state.moradores.map(m=>[esc(m.nome),esc(m.email),esc(m.cpf),esc(m.celular),esc(m.unidade||[m.bloco,m.apartamento].filter(Boolean).join(' - ')),`${esc(m.placa_veiculo)}<br>${placaThumb(m)}`,pessoasHtml(m),condName(m.condominio_id),actions('mor',m.id)]));}
function renderPortaria(){if($('portariaList')) $('portariaList').innerHTML=table(['Nome','CPF','Celular','E-mail/Login','Condomínio','Ações'],state.portaria.map(p=>[esc(p.nome),esc(p.cpf),esc(p.celular),esc(p.email),condName(p.condominio_id),actions('por',p.id)]));}
function renderLancamentos(){if(!$('lancamentosList'))return; $('lancamentosList').innerHTML=table(['Data','Título','Categoria','Tipo','Valor','Anexos','Condomínio','Ações'],state.lancamentos.map(l=>[esc(l.data_lancamento),esc(l.titulo),esc(l.categoria),esc(l.tipo),money(l.valor),anexosBtns(l),condName(l.condominio_id),actions('lan',l.id)]));}
function anexosBtns(l){const imgs=parseJson(l.imagens,[]),docs=parseJson(l.documentos,[]); return `${imgs.length?`<button class="mini-btn" onclick="showImages('${l.id}')">Imagens (${imgs.length})</button>`:''} ${docs.length?`<button class="mini-btn" onclick="showDocs('${l.id}')">Documentos (${docs.length})</button>`:''}`||'-'}
function renderAvisosAdmin(){if($('avisosList')) $('avisosList').innerHTML=state.avisos.map(a=>`<div class="oc-card"><strong>${esc(a.titulo)}</strong><p>${esc(a.texto)}</p><small>${condName(a.condominio_id)} · ${new Date(a.created_at||Date.now()).toLocaleString('pt-BR')}</small>${a.imagem?`<img src="${a.imagem}" class="notice-img">`:''}</div>`).join('')||'<p>Nenhum aviso enviado.</p>';}
window.editItem=(type,id)=>{const map={cond:['condominios','condominioId'],mor:['moradores','moradorId'],por:['portaria','portariaId'],lan:['lancamentos','lancamentoId']}; const [t,h]=map[type]; const o=state[t].find(x=>x.id===id); if(!o)return; $(h).value=o.id; if(type==='cond'){condNome.value=o.nome||'';condEndereco.value=o.endereco||'';condCnpj.value=o.cnpj||'';condResponsavel.value=o.responsavel||''} if(type==='mor'){moradorNome.value=o.nome||'';moradorEmail.value=o.email||'';moradorSenha.value='';moradorCpf.value=o.cpf||'';moradorCelular.value=o.celular||'';moradorCondominio.value=o.condominio_id||'';moradorBloco.value=o.bloco||'';moradorApartamento.value=o.apartamento||'';moradorUnidade.value=o.unidade||'';moradorPlaca.value=o.placa_veiculo||'';moradorPessoas.value=parseJson(o.pessoas_vinculadas,[]).map(p=>`${p.nome||''} - ${p.cpf||''}`).join('\n'); openEditModal(o)} if(type==='por'){portariaNome.value=o.nome||'';portariaCpf.value=o.cpf||'';portariaCelular.value=o.celular||'';portariaEmail.value=o.email||'';portariaSenha.value='';portariaCondominio.value=o.condominio_id||''} if(type==='lan'){lancamentoTitulo.value=o.titulo||'';lancamentoCategoria.value=o.categoria||'';lancamentoValor.value=o.valor||'';lancamentoData.value=o.data_lancamento||'';lancamentoTipo.value=o.tipo||'despesa';lancamentoDescricao.value=o.descricao||'';lancamentoCondominio.value=o.condominio_id||''} toast('Registro carregado para edição.');}
window.deleteItem=(t,id)=>removeRow({cond:'condominios',mor:'moradores',por:'portaria',lan:'lancamentos'}[t],id);
function parsePessoas(txt){return txt.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>{const [nome,...cpf]=x.split('-'); return {nome:nome.trim(),cpf:cpf.join('-').trim()};});}
function activeTab(id){document.querySelectorAll('#adminPanel .tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id)); document.querySelectorAll('#adminPanel .tab-content').forEach(t=>t.classList.toggle('active',t.id==='tab-'+id));}
document.querySelectorAll('#adminPanel .tabs button').forEach(b=>b.onclick=()=>activeTab(b.dataset.tab));
document.querySelectorAll('[data-logout]').forEach(b=>b.onclick=()=>{state.admin=null;state.morador=null;state.portariaUser=null;show('loginArea')});
adminLoginForm.onsubmit=e=>{e.preventDefault(); if(adminEmail.value.trim().toLowerCase()==='admin@arquipelago.com'&&adminSenha.value==='admin123'){state.admin=true;show('adminPanel');renderBadges()}else toast('Login administrativo inválido.')}
moradorLoginForm.onsubmit=e=>{e.preventDefault(); const m=state.moradores.find(x=>x.condominio_id===moradorLoginCondominio.value&&x.email?.toLowerCase()===moradorLoginEmail.value.trim().toLowerCase()&&x.senha===moradorLoginSenha.value); if(!m)return toast('Login do morador inválido.'); state.morador=m; renderMoradorPanel(); show('moradorPanel')}
portariaLoginForm.onsubmit=e=>{e.preventDefault(); const p=state.portaria.find(x=>x.condominio_id===portariaLoginCondominio.value&&x.email?.toLowerCase()===portariaLoginEmail.value.trim().toLowerCase()&&x.senha===portariaLoginSenha.value); if(!p)return toast('Login da portaria inválido.'); state.portariaUser=p; renderPortariaPanel(); show('portariaPanel')}
condominioForm.onsubmit=async e=>{e.preventDefault(); await upsert('condominios',{id:condominioId.value||uid(),nome:condNome.value,endereco:condEndereco.value,cnpj:condCnpj.value,responsavel:condResponsavel.value}); e.target.reset(); toast('Condomínio salvo.')}
moradorForm.onsubmit=async e=>{e.preventDefault(); const old=state.moradores.find(m=>m.id===moradorId.value)||{}; const foto=moradorFotoPlacaFile.files[0]?await fileToData(moradorFotoPlacaFile.files[0]):old.foto_placa_data; const unidade=moradorUnidade.value||[moradorBloco.value,moradorApartamento.value].filter(Boolean).join(' - '); await upsert('moradores',{...old,id:moradorId.value||uid(),nome:moradorNome.value,email:moradorEmail.value,senha:moradorSenha.value||old.senha||'123456',cpf:moradorCpf.value,celular:moradorCelular.value,condominio_id:moradorCondominio.value,bloco:moradorBloco.value,apartamento:moradorApartamento.value,unidade,placa_veiculo:moradorPlaca.value,pessoas_vinculadas:JSON.stringify(parsePessoas(moradorPessoas.value)),foto_placa_data:foto}); e.target.reset(); toast('Morador salvo.')}
senhaMoradorForm.onsubmit=async e=>{e.preventDefault(); const m=state.moradores.find(x=>x.id===senhaMoradorSelect.value); if(!m)return; await upsert('moradores',{...m,senha:novaSenhaMorador.value}); e.target.reset(); toast('Senha atualizada.')}
portariaForm.onsubmit=async e=>{e.preventDefault(); const old=state.portaria.find(p=>p.id===portariaId.value)||{}; await upsert('portaria',{...old,id:portariaId.value||uid(),condominio_id:portariaCondominio.value,nome:portariaNome.value,cpf:portariaCpf.value,celular:portariaCelular.value,email:portariaEmail.value,senha:portariaSenha.value||old.senha||'123456'}); e.target.reset(); toast('Portaria salva.')}
lancamentoForm.onsubmit=async e=>{e.preventDefault(); const old=state.lancamentos.find(l=>l.id===lancamentoId.value)||{}; const imgs=[...parseJson(old.imagens,[]),...(await filesToData(lancamentoImagens))]; const docs=[...parseJson(old.documentos,[]),...(await filesToData(lancamentoDocs))]; await upsert('lancamentos',{...old,id:lancamentoId.value||uid(),condominio_id:lancamentoCondominio.value,titulo:lancamentoTitulo.value,categoria:lancamentoCategoria.value,valor:Number(lancamentoValor.value),data_lancamento:lancamentoData.value||today(),tipo:lancamentoTipo.value,descricao:lancamentoDescricao.value,imagens:JSON.stringify(imgs),documentos:JSON.stringify(docs)}); e.target.reset(); toast('Lançamento salvo.')}
avisoForm.onsubmit=async e=>{e.preventDefault(); await upsert('avisos',{id:uid(),condominio_id:avisoCondominio.value,titulo:avisoTitulo.value,texto:avisoTexto.value,imagem:await fileToData(avisoImagem.files[0]),lidos:JSON.stringify([]),created_at:new Date().toISOString()}); e.target.reset(); toast('Aviso enviado.')}
function renderConversasAdmin(){if(!$('msgMoradores'))return; let msgs=state.mensagens.filter(m=>m.destinatario==='admin'||m.remetente==='admin'); if(msgFiltroCondominio?.value) msgs=msgs.filter(m=>m.condominio_id===msgFiltroCondominio.value); const keys=[...new Set(msgs.map(m=>m.morador_id||m.portaria_id).filter(Boolean))]; msgMoradores.innerHTML=keys.map(id=>{const mor=state.moradores.find(m=>m.id===id), por=state.portaria.find(p=>p.id===id); return `<button class="mini-btn conv-btn" onclick="abrirConversaAdmin('${mor?'morador':'portaria'}','${id}')">${esc(mor?.nome||por?.nome)}<br><small>${mor?'Morador':'Portaria'} · ${condName((mor||por).condominio_id)}</small></button>`}).join('')||'<p>Nenhuma conversa.</p>';}
carregarMensagens.onclick=renderConversasAdmin;
window.abrirConversaAdmin=(tipo,id)=>{state.conversa={tipo,id}; adminReplyForm.classList.remove('hidden'); const msgs=state.mensagens.filter(m=>(tipo==='morador'?m.morador_id===id:m.portaria_id===id)&&(m.destinatario==='admin'||m.remetente==='admin')).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)); msgs.forEach(m=>{if(m.destinatario==='admin')m.lida_admin=true}); saveRead(); msgConversa.innerHTML=msgs.map(messageHtml).join('')||'<p>Sem mensagens.</p>'; renderBadges();}
adminReplyForm.onsubmit=async e=>{e.preventDefault(); if(!state.conversa)return; const alvo=state.conversa; const base=alvo.tipo==='morador'?state.moradores.find(m=>m.id===alvo.id):state.portaria.find(p=>p.id===alvo.id); await upsert('mensagens',{id:uid(),condominio_id:base.condominio_id,morador_id:alvo.tipo==='morador'?alvo.id:null,portaria_id:alvo.tipo==='portaria'?alvo.id:null,remetente:'admin',destinatario:alvo.tipo,texto:adminReplyText.value,anexo_imagem:await fileToData(adminReplyImg.files[0]),lida_admin:true,lida_morador:false,lida_portaria:false,created_at:new Date().toISOString()}); adminReplyForm.reset(); abrirConversaAdmin(alvo.tipo,alvo.id); toast('Resposta enviada.')}
function messageHtml(m){return `<div class="message ${m.remetente==='admin'?'admin':''}"><strong>${labelRem(m.remetente)}</strong><p>${esc(m.texto)}</p>${m.anexo_imagem?`<img src="${m.anexo_imagem}" class="msg-img">`:''}<small>${new Date(m.created_at||Date.now()).toLocaleString('pt-BR')}</small></div>`}
function labelRem(r){return {admin:'Administração',morador:'Morador',portaria:'Portaria'}[r]||r}
async function sendMsg({texto,img,remetente,destinatario,morador_id,portaria_id,condominio_id}){await upsert('mensagens',{id:uid(),condominio_id, morador_id:morador_id||null, portaria_id:portaria_id||null, remetente,destinatario,texto,anexo_imagem:img,lida_admin:destinatario!=='admin',lida_morador:destinatario!=='morador',lida_portaria:destinatario!=='portaria',created_at:new Date().toISOString()});}
function renderMoradorPanel(){const m=state.morador; if(!m)return; moradorTitulo.textContent='Olá, '+m.nome; moradorSubtitulo.textContent='Unidade '+(m.unidade||'-')+' · '+condName(m.condominio_id); moradorCondNome.textContent=condName(m.condominio_id); const lans=state.lancamentos.filter(l=>l.condominio_id===m.condominio_id); moradorTotal.textContent=money(lans.filter(l=>l.tipo!=='receita').reduce((s,l)=>s+Number(l.valor||0),0)); moradorQtd.textContent=lans.length; moradorLancamentos.innerHTML=table(['Data','Título','Categoria','Tipo','Valor','Anexos'],lans.map(l=>[esc(l.data_lancamento),esc(l.titulo),esc(l.categoria),esc(l.tipo),money(l.valor),anexosBtns(l)])); renderMoradorAvisos(); renderMoradorMsgs(); renderBadges();}
function renderMoradorAvisos(){const m=state.morador; const avisos=state.avisos.filter(a=>a.condominio_id===m.condominio_id); moradorAvisos.innerHTML=avisos.map(a=>`<div class="oc-card" onclick="markAvisoRead('${a.id}')"><strong>${esc(a.titulo)}</strong><p>${esc(a.texto)}</p>${a.imagem?`<img src="${a.imagem}" class="notice-img">`:''}<small>${new Date(a.created_at||Date.now()).toLocaleString('pt-BR')}</small></div>`).join('')||'<p>Nenhum aviso.</p>';}
function renderMoradorMsgs(){const m=state.morador; const admin=state.mensagens.filter(x=>x.morador_id===m.id&&(x.destinatario==='admin'||x.remetente==='admin')); const port=state.mensagens.filter(x=>x.morador_id===m.id&&(x.destinatario==='portaria'||x.remetente==='portaria')); moradorMensagensAdmin.innerHTML=admin.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)).map(messageHtml).join('')||'<p>Nenhuma mensagem.</p>'; moradorMensagensPortaria.innerHTML=port.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)).map(messageHtml).join('')||'<p>Nenhuma mensagem.</p>'; admin.forEach(x=>{if(x.destinatario==='morador')x.lida_morador=true}); port.forEach(x=>{if(x.destinatario==='morador')x.lida_morador=true}); saveRead();}
moradorMsgAdminForm.onsubmit=async e=>{e.preventDefault(); if(!moradorMsgAdminTexto.value.trim())return; await sendMsg({texto:moradorMsgAdminTexto.value,img:await fileToData(moradorMsgAdminImg.files[0]),remetente:'morador',destinatario:'admin',morador_id:state.morador.id,condominio_id:state.morador.condominio_id}); e.target.reset(); toast('Mensagem enviada.'); renderMoradorPanel();}
moradorMsgPortariaForm.onsubmit=async e=>{e.preventDefault(); if(!moradorMsgPortariaTexto.value.trim())return; await sendMsg({texto:moradorMsgPortariaTexto.value,img:await fileToData(moradorMsgPortariaImg.files[0]),remetente:'morador',destinatario:'portaria',morador_id:state.morador.id,condominio_id:state.morador.condominio_id}); e.target.reset(); toast('Mensagem enviada.'); renderMoradorPanel();}
function renderPortariaPanel(){const p=state.portariaUser;if(!p)return; portariaTitulo.textContent='Olá, '+(p.nome||'Portaria'); portariaSubtitulo.textContent='Condomínio: '+condName(p.condominio_id); portariaFiltroCond.value=p.condominio_id; portariaMsgCond.value=p.condominio_id; renderPortariaUnidades(); renderPortariaMoradores(); renderPortariaConversas(); renderBadges();}
function renderPortariaUnidades(){const cond=portariaMsgCond.value||portariaFiltroCond.value; const uns=[...new Set(state.moradores.filter(m=>!cond||m.condominio_id===cond).map(m=>m.unidade).filter(Boolean))]; [portariaFiltroUnidade,portariaMsgUnidade].forEach(sel=>{if(!sel)return; const v=sel.value; sel.innerHTML='<option value="">Todas as unidades</option>'+uns.map(u=>`<option>${esc(u)}</option>`).join(''); sel.value=v;}); renderPortariaMoradorSelect();}
function renderPortariaMoradorSelect(){const cond=portariaMsgCond.value, un=portariaMsgUnidade.value; const rows=state.moradores.filter(m=>(!cond||m.condominio_id===cond)&&(!un||m.unidade===un)); portariaMsgMorador.innerHTML='<option value="">Selecione o morador</option>'+rows.map(m=>`<option value="${m.id}">${esc(m.nome)} - ${esc(m.cpf||'')}</option>`).join('');}
function renderPortariaMoradores(){const cond=portariaFiltroCond.value||state.portariaUser?.condominio_id, un=portariaFiltroUnidade.value, q=(portariaBusca.value||'').toLowerCase(); const rows=state.moradores.filter(m=>(!cond||m.condominio_id===cond)&&(!un||m.unidade===un)&&(!q||JSON.stringify(m).toLowerCase().includes(q))); portariaMoradoresList.innerHTML=table(['Nome','CPF','Unidade','Condomínio','Vinculados'],rows.map(m=>[esc(m.nome),esc(m.cpf),esc(m.unidade),condName(m.condominio_id),pessoasHtml(m)]));}
function renderPortariaConversas(){const p=state.portariaUser;if(!p)return; const msgs=state.mensagens.filter(m=>m.destinatario==='portaria'||m.remetente==='portaria').filter(m=>m.condominio_id===p.condominio_id); portariaConversas.innerHTML=msgs.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)).map(messageHtml).join('')||'<p>Nenhuma mensagem.</p>'; msgs.forEach(m=>{if(m.destinatario==='portaria')m.lida_portaria=true}); saveRead();}
portariaFiltroCond.onchange=()=>{renderPortariaUnidades();renderPortariaMoradores()}; portariaFiltroUnidade.onchange=renderPortariaMoradores; portariaBusca.oninput=renderPortariaMoradores; portariaMsgCond.onchange=renderPortariaUnidades; portariaMsgUnidade.onchange=renderPortariaMoradorSelect;
portariaMsgForm.onsubmit=async e=>{e.preventDefault(); const m=state.moradores.find(x=>x.id===portariaMsgMorador.value); if(!m)return; await sendMsg({texto:portariaMsgTexto.value,img:await fileToData(portariaMsgImg.files[0]),remetente:'portaria',destinatario:'morador',morador_id:m.id,portaria_id:state.portariaUser.id,condominio_id:m.condominio_id}); e.target.reset(); portariaMsgCond.value=state.portariaUser.condominio_id; renderPortariaUnidades(); toast('Mensagem enviada ao morador.');}
function saveRead(){ if(useSupabase){state.mensagens.forEach(m=>db.from('mensagens').update({lida_admin:m.lida_admin,lida_morador:m.lida_morador,lida_portaria:m.lida_portaria}).eq('id',m.id)); state.avisos.forEach(a=>db.from('avisos').update({lidos:a.lidos}).eq('id',a.id));} else {localSave('mensagens'); localSave('avisos');}}
window.markAvisoRead=id=>{const a=state.avisos.find(x=>x.id===id); if(a&&state.morador){const l=parseJson(a.lidos,[]); if(!l.includes(state.morador.id)){l.push(state.morador.id); a.lidos=JSON.stringify(l); saveRead(); renderBadges();}}}
function renderBadges(){setBadge('badgeAdminMsgs',state.mensagens.filter(m=>m.destinatario==='admin'&&!m.lida_admin).length); setBadge('badgeAdminPortaria',state.mensagens.filter(m=>m.remetente==='portaria'&&m.destinatario==='admin'&&!m.lida_admin).length); if(state.morador){const mid=state.morador.id; setBadge('badgeMoradorAvisos',state.avisos.filter(a=>a.condominio_id===state.morador.condominio_id&&!parseJson(a.lidos,[]).includes(mid)).length); setBadge('badgeMoradorAdmin',state.mensagens.filter(m=>m.morador_id===mid&&m.destinatario==='morador'&&m.remetente==='admin'&&!m.lida_morador).length); setBadge('badgeMoradorPortaria',state.mensagens.filter(m=>m.morador_id===mid&&m.destinatario==='morador'&&m.remetente==='portaria'&&!m.lida_morador).length);} if(state.portariaUser)setBadge('badgePortariaMsgs',state.mensagens.filter(m=>m.condominio_id===state.portariaUser.condominio_id&&m.destinatario==='portaria'&&!m.lida_portaria).length);}
function hideModal(){modal.classList.add('hidden'); modalBody.innerHTML=''} window.hideModal=hideModal; modalClose.onclick=hideModal;
function showModal(html){modalBody.innerHTML=html; modal.classList.remove('hidden')}
window.showPlate=id=>{const m=state.moradores.find(x=>x.id===id); const img=m?.foto_placa_data||m?.foto_placa_url; if(img)showModal(`<h3>Placa do veículo</h3><img src="${img}" class="modal-img">`)};
window.showPessoas=id=>{const m=state.moradores.find(x=>x.id===id); const ps=parseJson(m?.pessoas_vinculadas,[]); showModal(`<h3>Pessoas vinculadas a ${esc(m?.nome)}</h3>`+table(['Nome','CPF'],ps.map(p=>[esc(p.nome),esc(p.cpf)])))};
function openEditModal(m){showModal(`<h3>Editar morador</h3><p>O cadastro foi carregado no formulário. Acrescente ou remova informações e clique em <b>Atualizar cadastro do morador</b>.</p><div class="info-grid"><span>Nome: ${esc(m.nome)}</span><span>CPF: ${esc(m.cpf)}</span><span>Unidade: ${esc(m.unidade)}</span><span>Placa: ${esc(m.placa_veiculo)}</span></div>`)}
window.showImages=(id,keep=false)=>{const l=state.lancamentos.find(x=>x.id===id), imgs=parseJson(l?.imagens,[]); if(!keep) state.slide=0; showModal(`<h3>${esc(l.titulo)} - imagens</h3><div class="slide-box"><button class="mini-btn" onclick="prevSlide('${id}')">‹</button><img src="${imgs[state.slide]?.data}" class="modal-img"><button class="mini-btn" onclick="nextSlide('${id}')">›</button></div><small>${state.slide+1} de ${imgs.length}</small>`)}
window.prevSlide=id=>{const imgs=parseJson(state.lancamentos.find(x=>x.id===id)?.imagens,[]); state.slide=(state.slide-1+imgs.length)%imgs.length; showImages(id,true)}; window.nextSlide=id=>{const imgs=parseJson(state.lancamentos.find(x=>x.id===id)?.imagens,[]); state.slide=(state.slide+1)%imgs.length; showImages(id,true)};
window.showDocs=id=>{const l=state.lancamentos.find(x=>x.id===id), docs=parseJson(l?.documentos,[]); showModal(`<h3>${esc(l.titulo)} - documentos</h3>`+docs.map((d,i)=>`<p><a class="mini-btn" href="${d.data}" target="_blank" download="${esc(d.name)}">Abrir PDF ${i+1}: ${esc(d.name)}</a></p>`).join(''))}
document.querySelectorAll('.morador-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.morador-tabs button').forEach(x=>x.classList.toggle('active',x===b)); document.querySelectorAll('.morador-content').forEach(x=>x.classList.toggle('active',x.id==='mtab-'+b.dataset.mtab)); if(state.morador)renderMoradorMsgs(); renderBadges();});
document.querySelectorAll('.portaria-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.portaria-tabs button').forEach(x=>x.classList.toggle('active',x===b)); document.querySelectorAll('.portaria-content').forEach(x=>x.classList.toggle('active',x.id==='ptab-'+b.dataset.ptab)); if(state.portariaUser)renderPortariaConversas(); renderBadges();});
exportCsv.onclick=()=>{const csv=['Data,Título,Categoria,Tipo,Valor,Condomínio'].concat(state.lancamentos.map(l=>[l.data_lancamento,l.titulo,l.categoria,l.tipo,l.valor,condName(l.condominio_id)].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(','))).join('\n'); download('lancamentos-arquipelago.csv',csv,'text/csv')}
exportJson.onclick=()=>download('backup-arquipelago.json',JSON.stringify(Object.fromEntries(tables.map(t=>[t,state[t]])),null,2),'application/json')
importJson.onchange=e=>{const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{try{const data=JSON.parse(r.result); tables.forEach(t=>{if(Array.isArray(data[t])){state[t]=data[t];localSave(t)}}); renderAll(); toast('Backup importado.')}catch{toast('Arquivo inválido.')}}; r.readAsText(f)}
function download(name,content,type){const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([content],{type})); a.download=name; a.click(); URL.revokeObjectURL(a.href)}
removeMoradorBtn.onclick=()=>removeRow('moradores',removeMoradorSelect.value); removeLancamentoBtn.onclick=()=>removeRow('lancamentos',removeLancamentoSelect.value);
loadAll();
