const SUPABASE_URL = 'https://apykziojynimjarwdwoe.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFweWt6aW9qeW5pbWphcndkd29lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI3MTA4MzcsImV4cCI6MjA5ODI4NjgzN30.g3NzSf94bLe__CJM8DZHPhYilsod2XtnasP5Di2iIHw';
const useSupabase = SUPABASE_URL.startsWith('http') && SUPABASE_ANON_KEY.length > 40;
const db = useSupabase ? window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
const $ = id => document.getElementById(id);
let state = { condominios:[], moradores:[], portaria:[], lancamentos:[], mensagens:[], ocorrencias:[], slas:[], admin:null, morador:null, portariaUser:null, conversaMoradorId:null };
const tables = ['condominios','moradores','portaria','lancamentos','mensagens','ocorrencias','slas'];
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function today(){return new Date().toISOString().slice(0,10)}
function uid(){return crypto.randomUUID ? crypto.randomUUID() : String(Date.now()+Math.random())}
function localLoad(){for(const t of tables) state[t]=JSON.parse(localStorage.getItem('arq_'+t)||'[]'); if(!state.condominios.length){state.condominios=[{id:uid(),nome:'Condomínio Reserva das Praias',endereco:'Manaus/AM',cnpj:'',responsavel:'Síndico'}];localSaveAll()} if(!state.slas.length){state.slas=[{id:uid(),categoria:'Administrativo',setor:'Administrativo',perfil:'Administrativo',dias:3},{id:uid(),categoria:'Engenharia',setor:'Engenharia',perfil:'Engenharia',dias:5},{id:uid(),categoria:'Financeiro',setor:'Financeiro',perfil:'Financeiro',dias:2}];localSaveAll()}}
function localSave(t){localStorage.setItem('arq_'+t,JSON.stringify(state[t]))} function localSaveAll(){tables.forEach(localSave)}
async function loadAll(){ if(useSupabase){for(const t of tables){const {data,error}=await db.from(t).select('*').order('created_at',{ascending:false}); if(!error) state[t]=data||[];}} else localLoad(); renderAll() }
async function upsert(t,obj){ if(!obj.id) obj.id=uid(); obj.updated_at=new Date().toISOString(); if(useSupabase){const {error}=await db.from(t).upsert(obj); if(error){toast(error.message); return false}} else {const i=state[t].findIndex(x=>x.id===obj.id); if(i>=0) state[t][i]=obj; else state[t].unshift(obj); localSave(t)} await loadAll(); return true }
async function removeRow(t,id){ if(!id) return; if(!confirm('Confirmar remoção?')) return; if(useSupabase){const {error}=await db.from(t).delete().eq('id',id); if(error){toast(error.message);return}} else {state[t]=state[t].filter(x=>x.id!==id); localSave(t)} await loadAll(); toast('Removido com sucesso.') }
function optCond(sel,first='Selecione o condomínio'){ if(!sel) return; const v=sel.value; sel.innerHTML=`<option value="">${first}</option>`+state.condominios.map(c=>`<option value="${c.id}">${c.nome}</option>`).join(''); sel.value=v; }
function optMor(sel,first='Selecione um morador'){ if(!sel) return; const v=sel.value; sel.innerHTML=`<option value="">${first}</option>`+state.moradores.map(m=>`<option value="${m.id}">${m.nome} - ${m.email}</option>`).join(''); sel.value=v; }
function optLanc(sel,first='Selecione um lançamento'){ if(!sel) return; const v=sel.value; sel.innerHTML=`<option value="">${first}</option>`+state.lancamentos.map(l=>`<option value="${l.id}">${l.titulo} - ${money(l.valor)}</option>`).join(''); sel.value=v; }
function condName(id){return state.condominios.find(c=>c.id===id)?.nome||'-'}
function show(view){['loginArea','adminPanel','moradorPanel','portariaPanel'].forEach(id=>$(id).classList.add('hidden')); $(view).classList.remove('hidden'); window.scrollTo(0,0)}
function renderAll(){['moradorLoginCondominio','portariaLoginCondominio','moradorCondominio','portariaCondominio','lancamentoCondominio','msgFiltroCondominio','ocCond','ocFiltroCond'].forEach(id=>optCond($(id),id.includes('Filtro')?'Todos os condomínios':'Selecione o condomínio')); optMor($('senhaMoradorSelect')); optMor($('removeMoradorSelect')); optLanc($('removeLancamentoSelect')); renderConds(); renderMoradores(); renderPortaria(); renderLancamentos(); renderSlas(); renderOcorrencias(); renderMensagensList(); if(state.morador) renderMoradorPanel(); }
function renderConds(){ $('condominiosList').innerHTML = table(['Nome','Endereço','CNPJ','Responsável','Ações'], state.condominios.map(c=>[c.nome,c.endereco||'',c.cnpj||'',c.responsavel||'',actions('cond',c.id)])); }
function renderMoradores(){ $('moradoresList').innerHTML = table(['Nome','E-mail','Unidade','CPF','Celular','Condomínio','Ações'], state.moradores.map(m=>[m.nome,m.email,m.unidade||'',m.cpf||'',m.celular||'',condName(m.condominio_id),actions('mor',m.id)])); }
function renderPortaria(){ $('portariaList').innerHTML = table(['Nome','CPF','Celular','E-mail/Login','Condomínio','Ações'], state.portaria.map(p=>[p.nome,p.cpf||'',p.celular||'',p.email,condName(p.condominio_id),actions('por',p.id)])); }
function renderLancamentos(){ $('lancamentosList').innerHTML = table(['Data','Título','Categoria','Tipo','Valor','Condomínio','Ações'], state.lancamentos.map(l=>[l.data_lancamento||'',l.titulo,l.categoria||'',l.tipo,money(l.valor),condName(l.condominio_id),actions('lan',l.id)])); }
function table(head,rows){ if(!rows.length) return '<p>Nenhum registro encontrado.</p>'; return `<table class="data-table"><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c??''}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function actions(type,id){return `<div class="row-actions"><button class="mini-btn" onclick="editItem('${type}','${id}')">Editar</button><button class="mini-btn danger" onclick="deleteItem('${type}','${id}')">Remover</button></div>`}
window.editItem=(type,id)=>{ const map={cond:['condominios','condominioId'],mor:['moradores','moradorId'],por:['portaria','portariaId'],lan:['lancamentos','lancamentoId']}; const [t,h]=map[type]; const o=state[t].find(x=>x.id===id); if(!o)return; $(h).value=o.id; if(type==='cond'){condNome.value=o.nome||'';condEndereco.value=o.endereco||'';condCnpj.value=o.cnpj||'';condResponsavel.value=o.responsavel||''}
 if(type==='mor'){moradorNome.value=o.nome||'';moradorEmail.value=o.email||'';moradorSenha.value='';moradorUnidade.value=o.unidade||'';moradorCpf.value=o.cpf||'';moradorCelular.value=o.celular||'';moradorPlaca.value=o.placa_veiculo||'';moradorMoradores.value=o.moradores_juntos||'';moradorFotoPlaca.value=o.foto_placa_url||'';moradorCondominio.value=o.condominio_id||''}
 if(type==='por'){portariaNome.value=o.nome||'';portariaCpf.value=o.cpf||'';portariaCelular.value=o.celular||'';portariaEmail.value=o.email||'';portariaSenha.value='';portariaCondominio.value=o.condominio_id||''}
 if(type==='lan'){lancamentoTitulo.value=o.titulo||'';lancamentoCategoria.value=o.categoria||'';lancamentoValor.value=o.valor||'';lancamentoData.value=o.data_lancamento||'';lancamentoTipo.value=o.tipo||'despesa';lancamentoDescricao.value=o.descricao||'';lancamentoCondominio.value=o.condominio_id||''}
 toast('Registro carregado para edição.'); }
window.deleteItem=(type,id)=>removeRow({cond:'condominios',mor:'moradores',por:'portaria',lan:'lancamentos'}[type],id);
function activeTab(id){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.tab-content').forEach(t=>t.classList.toggle('active',t.id==='tab-'+id))}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>activeTab(b.dataset.tab));
document.querySelectorAll('[data-logout]').forEach(b=>b.onclick=()=>{state.admin=null;state.morador=null;state.portariaUser=null;show('loginArea')});
adminLoginForm.onsubmit=e=>{e.preventDefault(); if(adminEmail.value.trim().toLowerCase()==='admin@arquipelago.com' && adminSenha.value==='admin123'){state.admin=true;show('adminPanel')} else toast('Login administrativo inválido.')}
moradorLoginForm.onsubmit=e=>{e.preventDefault(); const m=state.moradores.find(x=>x.condominio_id===moradorLoginCondominio.value && x.email.toLowerCase()===moradorLoginEmail.value.trim().toLowerCase() && x.senha===moradorLoginSenha.value); if(!m)return toast('Login do morador inválido.'); state.morador=m; renderMoradorPanel(); show('moradorPanel')}
portariaLoginForm.onsubmit=e=>{e.preventDefault(); const p=state.portaria.find(x=>x.condominio_id===portariaLoginCondominio.value && x.email.toLowerCase()===portariaLoginEmail.value.trim().toLowerCase() && x.senha===portariaLoginSenha.value); if(!p)return toast('Login da portaria inválido.'); state.portariaUser=p; renderPortariaPanel(); show('portariaPanel')}
condominioForm.onsubmit=async e=>{e.preventDefault(); await upsert('condominios',{id:condominioId.value||uid(),nome:condNome.value,endereco:condEndereco.value,cnpj:condCnpj.value,responsavel:condResponsavel.value}); e.target.reset(); toast('Condomínio salvo.')}
moradorForm.onsubmit=async e=>{e.preventDefault(); const old=state.moradores.find(m=>m.id===moradorId.value); await upsert('moradores',{id:moradorId.value||uid(),nome:moradorNome.value,email:moradorEmail.value,senha:moradorSenha.value||old?.senha||'123456',unidade:moradorUnidade.value,cpf:moradorCpf.value,celular:moradorCelular.value,placa_veiculo:moradorPlaca.value,moradores_juntos:moradorMoradores.value,foto_placa_url:moradorFotoPlaca.value,condominio_id:moradorCondominio.value}); e.target.reset(); toast('Morador salvo.')}
senhaMoradorForm.onsubmit=async e=>{e.preventDefault(); const m=state.moradores.find(x=>x.id===senhaMoradorSelect.value); if(!m)return; m.senha=novaSenhaMorador.value; await upsert('moradores',m); e.target.reset(); toast('Senha atualizada.')}
portariaForm.onsubmit=async e=>{e.preventDefault(); const old=state.portaria.find(p=>p.id===portariaId.value); await upsert('portaria',{id:portariaId.value||uid(),condominio_id:portariaCondominio.value,nome:portariaNome.value,cpf:portariaCpf.value,celular:portariaCelular.value,email:portariaEmail.value,senha:portariaSenha.value||old?.senha||'123456'}); e.target.reset(); toast('Login da portaria salvo.')}
lancamentoForm.onsubmit=async e=>{e.preventDefault(); await upsert('lancamentos',{id:lancamentoId.value||uid(),condominio_id:lancamentoCondominio.value,titulo:lancamentoTitulo.value,categoria:lancamentoCategoria.value,valor:Number(lancamentoValor.value),data_lancamento:lancamentoData.value||today(),tipo:lancamentoTipo.value,descricao:lancamentoDescricao.value}); e.target.reset(); toast('Lançamento salvo.')}
function renderSlas(){slaList.innerHTML=state.slas.map(s=>`<div class="oc-card"><strong>${s.categoria}</strong><p>${s.setor||''} · Perfil: ${s.perfil||''} · SLA ${s.dias||0} dia(s)</p></div>`).join('')||'<p>Nenhuma categoria cadastrada.</p>'}
slaForm.onsubmit=async e=>{e.preventDefault(); await upsert('slas',{id:uid(),categoria:slaCategoria.value,setor:slaSetor.value,responsavel:slaResponsavel.value,perfil:slaPerfil.value,dias:Number(slaDias.value||0)}); e.target.reset(); toast('Categoria salva.')}
ocorrenciaForm.onsubmit=async e=>{e.preventDefault(); const count=state.ocorrencias.length+1; await upsert('ocorrencias',{id:uid(),numero:'OC-'+String(count).padStart(4,'0'),condominio_id:ocCond.value,unidade:ocUnidade.value,solicitante:ocSolicitante.value,categoria:ocCategoria.value,prioridade:ocPrioridade.value,descricao:ocDescricao.value,anexos:ocAnexos.value,status:'aberta',data_abertura:today()}); e.target.reset(); toast('Ocorrência registrada.')}
function renderOcorrencias(){ let rows=state.ocorrencias; if(ocFiltroCond?.value) rows=rows.filter(o=>o.condominio_id===ocFiltroCond.value); if(ocFiltroStatus?.value) rows=rows.filter(o=>o.status===ocFiltroStatus.value); if(ocBusca?.value) rows=rows.filter(o=>JSON.stringify(o).toLowerCase().includes(ocBusca.value.toLowerCase())); statAbertas.textContent=state.ocorrencias.filter(o=>o.status!=='concluida').length; statConcluidas.textContent=state.ocorrencias.filter(o=>o.status==='concluida').length; statVencidas.textContent=state.ocorrencias.filter(o=>o.status!=='concluida' && Math.ceil((new Date()-new Date(o.data_abertura))/(864e5))>3).length; ocorrenciasList.innerHTML=rows.map(o=>`<div class="oc-card"><strong>${o.numero} · ${o.categoria} · ${o.solicitante||'Solicitante'}</strong><p>${o.descricao}</p><p><b>${condName(o.condominio_id)}</b> ${o.unidade?'- Unidade '+o.unidade:''}</p><div class="badges"><span class="badge">${o.status}</span><span class="badge ${o.prioridade==='urgente'?'red':''}">${o.prioridade}</span><button class="mini-btn" onclick="setOcStatus('${o.id}','em_andamento')">Em andamento</button><button class="mini-btn" onclick="setOcStatus('${o.id}','concluida')">Concluir</button><button class="mini-btn danger" onclick="removeRow('ocorrencias','${o.id}')">Remover</button></div></div>`).join('')||'<p>Nenhuma ocorrência cadastrada.</p>'}
window.setOcStatus=async(id,status)=>{const o=state.ocorrencias.find(x=>x.id===id);if(o){o.status=status;if(status==='concluida')o.data_conclusao=today();await upsert('ocorrencias',o)}}; ocFiltroCond.onchange=renderOcorrencias; ocFiltroStatus.onchange=renderOcorrencias; ocBusca.oninput=renderOcorrencias;
function renderMensagensList(){ const msgs=state.mensagens; const ids=[...new Set(msgs.map(m=>m.morador_id))]; msgMoradores.innerHTML=ids.map(id=>{const m=state.moradores.find(x=>x.id===id);return m?`<button class="mini-btn" onclick="abrirConversa('${id}')">${m.nome}<br><small>${condName(m.condominio_id)}</small></button>`:''}).join('')||'<p>Nenhuma mensagem encontrada.</p>' }
carregarMensagens.onclick=renderMensagensList; window.abrirConversa=(id)=>{state.conversaMoradorId=id; adminReplyForm.classList.remove('hidden'); const m=state.moradores.find(x=>x.id===id); const msgs=state.mensagens.filter(x=>x.morador_id===id).sort((a,b)=>new Date(a.created_at||0)-new Date(b.created_at||0)); msgConversa.innerHTML=`<h4>${m?.nome||''}</h4>`+msgs.map(x=>`<div class="message ${x.remetente==='admin'?'admin':''}"><strong>${x.remetente==='admin'?'Administração':'Morador'}</strong>${x.texto}</div>`).join('') }
adminReplyForm.onsubmit=async e=>{e.preventDefault(); if(!state.conversaMoradorId)return; await upsert('mensagens',{id:uid(),morador_id:state.conversaMoradorId,condominio_id:state.moradores.find(m=>m.id===state.conversaMoradorId)?.condominio_id,remetente:'admin',texto:adminReplyText.value,created_at:new Date().toISOString()}); adminReplyText.value=''; abrirConversa(state.conversaMoradorId); toast('Resposta enviada.')}
function renderPortariaPanel(){const p=state.portariaUser; if(!p)return; portariaTitulo.textContent='Olá, '+(p.nome||'Portaria'); portariaSubtitulo.textContent='Condomínio: '+condName(p.condominio_id); portariaCondNome.textContent=condName(p.condominio_id)}
function renderMoradorPanel(){const m=state.morador; if(!m)return; moradorTitulo.textContent='Olá, '+m.nome; moradorSubtitulo.textContent='Unidade '+(m.unidade||'-')+' · '+condName(m.condominio_id); moradorCondNome.textContent=condName(m.condominio_id); const lans=state.lancamentos.filter(l=>l.condominio_id===m.condominio_id); moradorTotal.textContent=money(lans.filter(l=>l.tipo!=='receita').reduce((s,l)=>s+Number(l.valor||0),0)); moradorQtd.textContent=lans.length; moradorLancamentos.innerHTML=table(['Data','Título','Categoria','Tipo','Valor'],lans.map(l=>[l.data_lancamento,l.titulo,l.categoria,l.tipo,money(l.valor)])); const msgs=state.mensagens.filter(x=>x.morador_id===m.id).sort((a,b)=>new Date(a.created_at||0)-new Date(b.created_at||0)); moradorMensagens.innerHTML=msgs.map(x=>`<div class="message ${x.remetente==='admin'?'admin':''}"><strong>${x.remetente==='admin'?'Administração':'Você'}</strong>${x.texto}</div>`).join('')||'<p>Nenhuma mensagem ainda.</p>'}
moradorMsgForm.onsubmit=async e=>{e.preventDefault(); if(!moradorMsgTexto.value.trim())return; await upsert('mensagens',{id:uid(),morador_id:state.morador.id,condominio_id:state.morador.condominio_id,remetente:'morador',texto:moradorMsgTexto.value,created_at:new Date().toISOString()}); moradorMsgTexto.value=''; toast('Mensagem enviada.'); renderMoradorPanel()}
exportCsv.onclick=()=>{const csv=['Data,Título,Categoria,Tipo,Valor,Condomínio'].concat(state.lancamentos.map(l=>[l.data_lancamento,l.titulo,l.categoria,l.tipo,l.valor,condName(l.condominio_id)].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(','))).join('\n'); download('lancamentos-arquipelago.csv',csv,'text/csv')}
exportJson.onclick=()=>download('backup-arquipelago.json',JSON.stringify(Object.fromEntries(tables.map(t=>[t,state[t]])),null,2),'application/json')
importJson.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);tables.forEach(t=>{if(Array.isArray(data[t])){state[t]=data[t];localSave(t)}});renderAll();toast('Backup importado.')}catch{toast('Arquivo inválido.')}};r.readAsText(f)}
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
removeMoradorBtn.onclick=()=>removeRow('moradores',removeMoradorSelect.value); removeLancamentoBtn.onclick=()=>removeRow('lancamentos',removeLancamentoSelect.value);
loadAll();
