const SUPABASE_URL = 'https://apykziojynimjarwdwoe.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFweWt6aW9qeW5pbWphcndkd29lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI3MTA4MzcsImV4cCI6MjA5ODI4NjgzN30.g3NzSf94bLe__CJM8DZHPhYilsod2XtnasP5Di2iIHw';
const useSupabase = SUPABASE_URL.startsWith('http') && SUPABASE_ANON_KEY.length > 40;
const db = useSupabase ? window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
const $ = id => document.getElementById(id);
const tables = ['condominios','moradores','portaria','lancamentos','mensagens','avisos'];
let state = {condominios:[],moradores:[],portaria:[],lancamentos:[],mensagens:[],avisos:[],admin:null,morador:null,portariaUser:null,conversa:null,slide:0,docSlide:0,noticeSlide:0};
const uid = () => crypto.randomUUID ? crypto.randomUUID() : String(Date.now()+Math.random());
const today = () => new Date().toISOString().slice(0,10);
const money = v => Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const monthLabel = d => { const dt = d ? new Date(String(d).slice(0,10)+'T12:00:00') : new Date(); return dt.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}).replace(/^./,c=>c.toUpperCase()); };
function groupByMonth(rows, dateGetter){ return rows.reduce((acc,item)=>{ const k=monthLabel(dateGetter(item)); (acc[k]=acc[k]||[]).push(item); return acc; },{}); }
function isHiddenForMorador(obj, mid){ return parseJson(obj?.ocultos,[]).includes(mid); }
function isMsgDeletedForMorador(obj, mid){ return parseJson(obj?.deleted_by,[]).includes('morador:'+mid); }
function isMsgDeletedForPortaria(obj, pid){ return parseJson(obj?.deleted_by,[]).includes('portaria:'+pid); }
const esc = v => String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(msg){const t=$('toast'); if(!t) return; t.textContent=msg; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),2600)}
function parseJson(v,d=[]){try{return typeof v==='string'?JSON.parse(v||'[]'):(v||d)}catch{return d}}
function condName(id){return state.condominios.find(c=>c.id===id)?.nome||'-'}
function localLoad(){tables.forEach(t=>state[t]=JSON.parse(localStorage.getItem('arq_'+t)||'[]')); if(!state.condominios.length){state.condominios=[{id:uid(),nome:'Condomínio Reserva das Praias',endereco:'Manaus/AM',responsavel:'Síndico'}]; localSaveAll();}}
function localSave(t){localStorage.setItem('arq_'+t,JSON.stringify(state[t]))} function localSaveAll(){tables.forEach(localSave)}
async function loadAll(){ if(useSupabase){for(const t of tables){const {data,error}=await db.from(t).select('*').order('created_at',{ascending:false}); if(!error) state[t]=data||[]; else if(t==='avisos') state[t]=[];}} else localLoad(); renderAll(); }
async function upsert(t,obj){obj.id=obj.id||uid(); obj.updated_at=new Date().toISOString(); if(useSupabase){const {error}=await db.from(t).upsert(obj); if(error){toast(error.message); return false;}} else {const i=state[t].findIndex(x=>x.id===obj.id); i>=0?state[t][i]=obj:state[t].unshift(obj); localSave(t);} await loadAll(); return true;}
async function removeRow(t,id){if(!id||!confirm('Confirmar remoção?'))return; if(useSupabase){const {error}=await db.from(t).delete().eq('id',id); if(error)return toast(error.message);}else{state[t]=state[t].filter(x=>x.id!==id); localSave(t);} await loadAll(); toast('Removido com sucesso.');}
async function fileToData(file){return new Promise((res,rej)=>{if(!file)return res(''); const r=new FileReader(); r.onload=()=>res(r.result); r.onerror=rej; r.readAsDataURL(file);});}
async function filesToData(input){return Promise.all([...((input&&input.files)||[])].map(async f=>({name:f.name,type:f.type,data:await fileToData(f)})));}
function optCond(sel,first='Selecione o condomínio'){if(!sel)return; const v=sel.value; sel.innerHTML=`<option value="">${first}</option>`+state.condominios.map(c=>`<option value="${c.id}">${esc(c.nome)}</option>`).join(''); sel.value=v;}
function optMor(sel,first='Selecione um morador'){if(!sel)return; const v=sel.value; sel.innerHTML=`<option value="">${first}</option>`+state.moradores.map(m=>`<option value="${m.id}">${esc(m.nome)} - ${esc(m.email)}</option>`).join(''); sel.value=v;}
function optLanc(sel){if(!sel)return; const v=sel.value; sel.innerHTML='<option value="">Selecione o lançamento</option>'+state.lancamentos.map(l=>`<option value="${l.id}">${esc(l.titulo)} - ${money(l.valor)}</option>`).join(''); sel.value=v;}
function table(head,rows){if(!rows.length)return '<p>Nenhum registro encontrado.</p>'; return `<table class="data-table"><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c??''}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function show(view){['loginArea','adminPanel','moradorPanel','portariaPanel'].forEach(id=>$(id)?.classList.add('hidden')); $(view)?.classList.remove('hidden'); window.scrollTo(0,0)}
function setBadge(id,n){const b=$(id); if(!b)return; b.textContent=n; b.classList.toggle('hidden',!n)}
function renderAll(){['moradorLoginCondominio','portariaLoginCondominio','moradorCondominio','portariaCondominio','lancamentoCondominio','avisoCondominio','msgFiltroCondominio','portariaFiltroCond','portariaMsgCond'].forEach(id=>optCond($(id),id.includes('Filtro')?'Todos os condomínios':'Selecione o condomínio')); optMor($('senhaMoradorSelect')); optMor($('removeMoradorSelect')); optLanc($('removeLancamentoSelect')); renderConds();renderMoradores();renderPortaria();renderLancamentos();renderAvisosAdmin();renderConversasAdmin();renderBadges(); if(state.morador)renderMoradorPanel(); if(state.portariaUser)renderPortariaPanel();}
function renderConds(){if($('condominiosList')) $('condominiosList').innerHTML=table(['Nome','Endereço','CNPJ','Responsável','Ações'],state.condominios.map(c=>[esc(c.nome),esc(c.endereco),esc(c.cnpj),esc(c.responsavel),actions('cond',c.id)]));}
function actions(t,id){return `<div class="row-actions"><button class="mini-btn" onclick="editItem('${t}','${id}')">Editar</button><button class="mini-btn danger" onclick="deleteItem('${t}','${id}')">Remover</button></div>`}
function pessoasHtml(m){const ps=parseJson(m.pessoas_vinculadas,[]); return ps.length?`<button class="mini-btn" onclick="showPessoas('${m.id}')">Exibir nomes vinculados</button>`:'-'}
function placaThumb(m){const img=m.foto_placa_data||m.foto_placa_url; return img?`<span class="plate-hover"><img src="${img}" class="plate-thumb"><span class="plate-preview"><img src="${img}"></span></span>`:''}
function renderMoradores(){if(!$('moradoresList'))return; const grupos={}; [...state.moradores].sort((a,b)=>moradorBlocoLabel(a).localeCompare(moradorBlocoLabel(b),'pt-BR',{numeric:true})||String(a.apartamento||'').localeCompare(String(b.apartamento||''),'pt-BR',{numeric:true})).forEach(m=>{const key=moradorBlocoLabel(m); (grupos[key]=grupos[key]||[]).push(m);}); $('moradoresList').innerHTML=Object.entries(grupos).map(([torre,rows],idx)=>`<details class="month-group" ${idx===0?'open':''}><summary>${esc(torre)} (${rows.length} morador${rows.length>1?'es':''})</summary>${table(['Nome','E-mail','CPF','Celular','Apartamento','Unidade','Veículo','Pessoas vinculadas','Condomínio','Ações'],rows.map(m=>[esc(m.nome),esc(m.email),esc(m.cpf),esc(m.celular),esc(m.apartamento||'-'),esc(m.unidade||[m.bloco,m.apartamento].filter(Boolean).join(' - ')),`${esc(m.placa_veiculo)}<br>${placaThumb(m)}`,pessoasHtml(m),condName(m.condominio_id),actions('mor',m.id)]))}</details>`).join('')||'<p>Nenhum morador cadastrado.</p>'; }
function renderPortaria(){if($('portariaList')) $('portariaList').innerHTML=table(['Nome','CPF','Celular','E-mail/Login','Condomínio','Ações'],state.portaria.map(p=>[esc(p.nome),esc(p.cpf),esc(p.celular),esc(p.email),condName(p.condominio_id),actions('por',p.id)]));}
function renderLancamentos(){if(!$('lancamentosList'))return; $('lancamentosList').innerHTML=table(['Data','Título','Descrição','Categoria','Tipo','Valor','Anexos','Condomínio','Ações'],state.lancamentos.map(l=>[esc(l.data_lancamento),esc(l.titulo),esc(l.descricao||'-'),esc(l.categoria),esc(l.tipo),money(l.valor),anexosBtns(l),condName(l.condominio_id),actions('lan',l.id)]));}
function anexosBtns(l){const imgs=parseJson(l.imagens,[]),docs=parseJson(l.documentos,[]); return `${imgs.length?`<button class="mini-btn" onclick="showImages('${l.id}')">Imagens (${imgs.length})</button>`:''} ${docs.length?`<button class="mini-btn" onclick="showDocs('${l.id}')">Documentos (${docs.length})</button>`:''}`||'-'}
function renderAvisosAdmin(){if(!$('avisosList'))return; const avisos=[...state.avisos].sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0)); const grupos=groupByMonth(avisos,a=>a.created_at); avisosList.innerHTML=Object.entries(grupos).map(([mes,items],idx)=>`<details class="month-group" ${idx===0?'open':''}><summary>${esc(mes)} (${items.length})</summary>${items.map(a=>{const imgs=avisoImages(a); return `<div class="oc-card"><strong>${esc(a.titulo)}</strong><p>${esc(a.texto)}</p><small>${condName(a.condominio_id)} · Postado em ${new Date(a.created_at||Date.now()).toLocaleString('pt-BR')}</small>${imgs.length?`<img src="${imgs[0].data}" class="notice-img hover-img" onclick="showAvisoImages('${a.id}')" title="Clique para ampliar">`:''}<div class="row-actions"><button class="mini-btn" onclick="showAvisoImages('${a.id}')">Imagens (${imgs.length})</button><button class="mini-btn danger" onclick="removeRow('avisos','${a.id}')">Remover aviso</button></div></div>`}).join('')}</details>`).join('')||'<p>Nenhum aviso enviado.</p>';}
window.editItem=(type,id)=>{const map={cond:['condominios','condominioId'],mor:['moradores','moradorId'],por:['portaria','portariaId'],lan:['lancamentos','lancamentoId']}; const [t,h]=map[type]; const o=state[t].find(x=>x.id===id); if(!o)return; $(h).value=o.id; if(type==='cond'){condNome.value=o.nome||'';condEndereco.value=o.endereco||'';condCnpj.value=o.cnpj||'';condResponsavel.value=o.responsavel||''} if(type==='mor'){moradorNome.value=o.nome||'';moradorEmail.value=o.email||'';moradorSenha.value='';moradorCpf.value=o.cpf||'';moradorCelular.value=o.celular||'';moradorCondominio.value=o.condominio_id||'';moradorBloco.value=o.bloco||'';moradorApartamento.value=o.apartamento||'';moradorUnidade.value=o.unidade||'';moradorPlaca.value=o.placa_veiculo||'';moradorPessoas.value=parseJson(o.pessoas_vinculadas,[]).map(p=>`${p.nome||''} - ${p.cpf||''}`).join('\n'); openEditModal(o)} if(type==='por'){portariaNome.value=o.nome||'';portariaCpf.value=o.cpf||'';portariaCelular.value=o.celular||'';portariaEmail.value=o.email||'';portariaSenha.value='';portariaCondominio.value=o.condominio_id||''} if(type==='lan'){lancamentoTitulo.value=o.titulo||'';lancamentoCategoria.value=o.categoria||'';lancamentoValor.value=o.valor||'';lancamentoData.value=o.data_lancamento||'';lancamentoTipo.value=o.tipo||'despesa';lancamentoDescricao.value=o.descricao||'';lancamentoCondominio.value=o.condominio_id||''} toast('Registro carregado para edição.');}
window.deleteItem=(t,id)=>removeRow({cond:'condominios',mor:'moradores',por:'portaria',lan:'lancamentos'}[t],id);
function parsePessoas(txt){return txt.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>{const [nome,...cpf]=x.split('-'); return {nome:nome.trim(),cpf:cpf.join('-').trim()};});}
function activeTab(id){document.querySelectorAll('#adminPanel .tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id)); document.querySelectorAll('#adminPanel .tab-content').forEach(t=>t.classList.toggle('active',t.id==='tab-'+id));}
document.querySelectorAll('#adminPanel .tabs button').forEach(b=>b.onclick=()=>activeTab(b.dataset.tab));
document.querySelectorAll('[data-logout]').forEach(b=>b.onclick=()=>{state.admin=null;state.morador=null;state.portariaUser=null;show('loginArea')});
adminLoginForm.onsubmit=e=>{e.preventDefault(); if(adminEmail.value.trim().toLowerCase()==='admin@arquipelago.com'&&adminSenha.value==='admin123'){state.admin=true;show('adminPanel');renderBadges()}else toast('Login administrativo inválido.')}
moradorLoginForm.onsubmit=e=>{e.preventDefault(); const m=state.moradores.find(x=>x.condominio_id===moradorLoginCondominio.value&&x.email?.toLowerCase()===moradorLoginEmail.value.trim().toLowerCase()&&x.senha===moradorLoginSenha.value); if(!m)return toast('Login do morador inválido.'); state.morador=m; renderMoradorPanel(); show('moradorPanel')}
portariaLoginForm.onsubmit=e=>{e.preventDefault(); const p=state.portaria.find(x=>x.condominio_id===portariaLoginCondominio.value&&x.email?.toLowerCase()===portariaLoginEmail.value.trim().toLowerCase()&&x.senha===portariaLoginSenha.value); if(!p)return toast('Login da portaria inválido.'); state.portariaUser=p; renderPortariaPanel(); show('portariaPanel')}
condominioForm.onsubmit=async e=>{e.preventDefault(); await upsert('condominios',{id:condominioId.value||uid(),nome:condNome.value,endereco:condEndereco.value,cnpj:condCnpj.value,responsavel:condResponsavel.value}); e.target.reset(); toast('Condomínio salvo.')}
moradorForm.onsubmit=async e=>{e.preventDefault(); const old=state.moradores.find(m=>m.id===moradorId.value)||{}; const foto=moradorFotoPlacaFile.files[0]?await fileToData(moradorFotoPlacaFile.files[0]):old.foto_placa_data; const unidade=moradorUnidade.value||[moradorBloco.value,moradorApartamento.value].filter(Boolean).join(' - '); await upsert('moradores',{...old,id:moradorId.value||uid(),nome:moradorNome.value,email:moradorEmail.value,senha:moradorSenha.value||old.senha||'123456',cpf:moradorCpf.value,celular:moradorCelular.value,condominio_id:moradorCondominio.value,bloco:moradorBloco.value,apartamento:moradorApartamento.value,unidade,placa_veiculo:moradorPlaca.value,pessoas_vinculadas:JSON.stringify(parsePessoas(moradorPessoas.value)),foto_placa_data:foto}); e.target.reset(); toast('Morador salvo.')}
senhaMoradorForm.onsubmit=async e=>{e.preventDefault(); const m=state.moradores.find(x=>x.id===senhaMoradorSelect.value); if(!m)return; await upsert('moradores',{...m,senha:novaSenhaMorador.value}); e.target.reset(); toast('Senha atualizada.')}
portariaForm.onsubmit=async e=>{e.preventDefault(); const old=state.portaria.find(p=>p.id===portariaId.value)||{}; await upsert('portaria',{...old,id:portariaId.value||uid(),condominio_id:portariaCondominio.value,nome:portariaNome.value,cpf:portariaCpf.value,celular:portariaCelular.value,email:portariaEmail.value,senha:portariaSenha.value||old.senha||'123456'}); e.target.reset(); toast('Portaria salva.')}
lancamentoForm.onsubmit=async e=>{e.preventDefault(); const old=state.lancamentos.find(l=>l.id===lancamentoId.value)||{}; const imgs=[...parseJson(old.imagens,[]),...(await filesToData(lancamentoImagens))]; const docs=[...parseJson(old.documentos,[]),...(await filesToData(lancamentoDocs))]; await upsert('lancamentos',{...old,id:lancamentoId.value||uid(),condominio_id:lancamentoCondominio.value,titulo:lancamentoTitulo.value,categoria:lancamentoCategoria.value,valor:Number(lancamentoValor.value),data_lancamento:lancamentoData.value||today(),tipo:lancamentoTipo.value,descricao:lancamentoDescricao.value,imagens:JSON.stringify(imgs),documentos:JSON.stringify(docs)}); e.target.reset(); toast('Lançamento salvo.')}
avisoForm.onsubmit=async e=>{e.preventDefault(); const imgs=await filesToData(avisoImagem); await upsert('avisos',{id:uid(),condominio_id:avisoCondominio.value,titulo:avisoTitulo.value,texto:avisoTexto.value,imagem:imgs[0]?.data||'',imagens:JSON.stringify(imgs),lidos:JSON.stringify([]),ocultos:JSON.stringify([]),created_at:new Date().toISOString()}); e.target.reset(); toast('Aviso enviado.')}
function renderConversasAdmin(){if(!$('msgMoradores'))return; let msgs=state.mensagens.filter(m=>m.destinatario==='admin'||m.remetente==='admin'); if(msgFiltroCondominio?.value) msgs=msgs.filter(m=>m.condominio_id===msgFiltroCondominio.value); const keys=[...new Set(msgs.map(m=>m.morador_id||m.portaria_id).filter(Boolean))]; msgMoradores.innerHTML=keys.map(id=>{const mor=state.moradores.find(m=>m.id===id), por=state.portaria.find(p=>p.id===id); const conv=msgs.filter(m=>(mor?m.morador_id===id:m.portaria_id===id)); const unread=conv.filter(m=>m.destinatario==='admin'&&!m.lida_admin).length; return `<button class="mini-btn conv-btn" onclick="abrirConversaAdmin('${mor?'morador':'portaria'}','${id}')">${esc(mor?.nome||por?.nome)}${unread?` <span class="notify-badge inline-badge">${unread}</span>`:''}<br><small>${mor?'Morador':'Portaria'} · ${condName((mor||por).condominio_id)}</small></button>`}).join('')||'<p>Nenhuma conversa.</p>';}
carregarMensagens.onclick=renderConversasAdmin;
window.abrirConversaAdmin=(tipo,id)=>{state.conversa={tipo,id}; adminReplyForm.classList.remove('hidden'); const msgs=state.mensagens.filter(m=>(tipo==='morador'?m.morador_id===id:m.portaria_id===id)&&(m.destinatario==='admin'||m.remetente==='admin')).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)); msgs.forEach(m=>{if(m.destinatario==='admin')m.lida_admin=true}); saveRead(); msgConversa.innerHTML=msgs.map(messageHtml).join('')||'<p>Sem mensagens.</p>'; renderBadges();}
adminReplyForm.onsubmit=async e=>{e.preventDefault(); if(!state.conversa)return; const alvo=state.conversa; const base=alvo.tipo==='morador'?state.moradores.find(m=>m.id===alvo.id):state.portaria.find(p=>p.id===alvo.id); await upsert('mensagens',{id:uid(),condominio_id:base.condominio_id,morador_id:alvo.tipo==='morador'?alvo.id:null,portaria_id:alvo.tipo==='portaria'?alvo.id:null,remetente:'admin',destinatario:alvo.tipo,texto:adminReplyText.value,anexo_imagem:await fileToData(adminReplyImg.files[0]),lida_admin:true,lida_morador:false,lida_portaria:false,created_at:new Date().toISOString()}); adminReplyForm.reset(); abrirConversaAdmin(alvo.tipo,alvo.id); toast('Resposta enviada.')}
function messageHtml(m){const del=state.morador?`<button class="mini-btn danger" onclick="deleteMsgForMorador('${m.id}')">Excluir mensagem</button>`:(state.portariaUser?`<button class="mini-btn danger" onclick="deleteMsgForPortaria('${m.id}')">Excluir mensagem</button>`:''); return `<div class="message ${m.remetente==='admin'?'admin':''}"><strong>${labelRem(m.remetente)}</strong><p>${esc(m.texto)}</p>${m.anexo_imagem?`<img src="${m.anexo_imagem}" class="msg-img">`:''}<small>${new Date(m.created_at||Date.now()).toLocaleString('pt-BR')}</small><div class="row-actions">${del}</div></div>`}
function labelRem(r){return {admin:'Administração',morador:'Morador',portaria:'Portaria'}[r]||r}
async function sendMsg({texto,img,remetente,destinatario,morador_id,portaria_id,condominio_id}){await upsert('mensagens',{id:uid(),condominio_id, morador_id:morador_id||null, portaria_id:portaria_id||null, remetente,destinatario,texto,anexo_imagem:img,lida_admin:destinatario!=='admin',lida_morador:destinatario!=='morador',lida_portaria:destinatario!=='portaria',created_at:new Date().toISOString()});}
function renderMoradorPanel(){const m=state.morador; if(!m)return; moradorTitulo.textContent='Olá, '+m.nome; moradorSubtitulo.textContent='Unidade '+(m.unidade||'-')+' · '+condName(m.condominio_id); moradorCondNome.textContent=condName(m.condominio_id); const lans=state.lancamentos.filter(l=>l.condominio_id===m.condominio_id).sort((a,b)=>new Date(b.data_lancamento||0)-new Date(a.data_lancamento||0)); moradorTotal.textContent=money(lans.filter(l=>l.tipo!=='receita').reduce((s,l)=>s+Number(l.valor||0),0)); moradorQtd.textContent=lans.length; const grupos=groupByMonth(lans,l=>l.data_lancamento); moradorLancamentos.innerHTML=Object.entries(grupos).map(([mes,items],idx)=>`<details class="month-group" ${idx===0?'open':''}><summary>${esc(mes)} (${items.length} lançamentos)</summary>${table(['Data','Título','Descrição','Categoria','Tipo','Valor','Anexos'],items.map(l=>[esc(l.data_lancamento),esc(l.titulo),esc(l.descricao||'-'),esc(l.categoria),esc(l.tipo),money(l.valor),anexosBtns(l)]))}</details>`).join('')||'<p>Nenhum lançamento.</p>'; renderMoradorAvisos(); renderMoradorMsgs(); renderBadges();}
function renderMoradorAvisos(){const m=state.morador; const avisos=state.avisos.filter(a=>a.condominio_id===m.condominio_id&&!isHiddenForMorador(a,m.id)).sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0)); const grupos=groupByMonth(avisos,a=>a.created_at); moradorAvisos.innerHTML=Object.entries(grupos).map(([mes,items],idx)=>`<details class="month-group" ${idx===0?'open':''}><summary>${esc(mes)} (${items.length} avisos)</summary>${items.map(a=>{const imgs=avisoImages(a); return `<div class="oc-card" onmouseenter="markAvisoRead('${a.id}')"><strong>${esc(a.titulo)}</strong><p>${esc(a.texto)}</p><small>Postado em ${new Date(a.created_at||Date.now()).toLocaleString('pt-BR')} · ${condName(a.condominio_id)}</small>${imgs.length?`<span class="notice-hover"><img src="${imgs[0].data}" class="notice-img hover-img"><span class="notice-preview"><img src="${imgs[0].data}"></span></span>`:''}<div class="row-actions">${imgs.length?`<button class="mini-btn" onclick="showAvisoImages('${a.id}')">Ver imagens (${imgs.length})</button>`:''}<button class="mini-btn" onclick="ocultarAvisoMorador('${a.id}')">Ocultar</button><button class="mini-btn danger" onclick="ocultarAvisoMorador('${a.id}')">Remover do meu painel</button></div></div>`}).join('')}</details>`).join('')||'<p>Nenhum aviso.</p>';}
function renderMoradorMsgs(){const m=state.morador; const base=state.mensagens.filter(x=>!isMsgDeletedForMorador(x,m.id)); const admin=base.filter(x=>x.morador_id===m.id&&(x.destinatario==='admin'||x.remetente==='admin')); const port=base.filter(x=>x.morador_id===m.id&&(x.destinatario==='portaria'||x.remetente==='portaria')); moradorMensagensAdmin.innerHTML=admin.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)).map(messageHtml).join('')||'<p>Nenhuma mensagem.</p>'; moradorMensagensPortaria.innerHTML=port.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)).map(messageHtml).join('')||'<p>Nenhuma mensagem.</p>'; admin.forEach(x=>{if(x.destinatario==='morador')x.lida_morador=true}); port.forEach(x=>{if(x.destinatario==='morador')x.lida_morador=true}); saveRead();}
moradorMsgAdminForm.onsubmit=async e=>{e.preventDefault(); if(!moradorMsgAdminTexto.value.trim())return; await sendMsg({texto:moradorMsgAdminTexto.value,img:await fileToData(moradorMsgAdminImg.files[0]),remetente:'morador',destinatario:'admin',morador_id:state.morador.id,condominio_id:state.morador.condominio_id}); e.target.reset(); toast('Mensagem enviada.'); renderMoradorPanel();}
moradorMsgPortariaForm.onsubmit=async e=>{e.preventDefault(); if(!moradorMsgPortariaTexto.value.trim())return; await sendMsg({texto:moradorMsgPortariaTexto.value,img:await fileToData(moradorMsgPortariaImg.files[0]),remetente:'morador',destinatario:'portaria',morador_id:state.morador.id,condominio_id:state.morador.condominio_id}); e.target.reset(); toast('Mensagem enviada.'); renderMoradorPanel();}
function renderPortariaPanel(){const p=state.portariaUser;if(!p)return; portariaTitulo.textContent='Olá, '+(p.nome||'Portaria'); portariaSubtitulo.textContent='Condomínio: '+condName(p.condominio_id); portariaFiltroCond.value=p.condominio_id; portariaMsgCond.value=p.condominio_id; renderPortariaUnidades(); renderPortariaMoradores(); renderPortariaConversas(); renderBadges();}
function moradorBlocoLabel(m){return (m.bloco||String(m.unidade||'').split('-')[0]||'Sem torre/bloco').trim()||'Sem torre/bloco'}
function renderPortariaUnidades(){const cond=portariaMsgCond.value||portariaFiltroCond.value||state.portariaUser?.condominio_id; const blocos=[...new Set(state.moradores.filter(m=>!cond||m.condominio_id===cond).map(moradorBlocoLabel).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR',{numeric:true})); [[portariaFiltroBloco,'Todas as torres/blocos'],[portariaMsgBloco,'Selecione a torre/bloco']].forEach(([sel,first])=>{if(!sel)return; const v=sel.value; sel.innerHTML=`<option value="">${first}</option>`+blocos.map(b=>`<option value="${esc(b)}">${esc(b)}</option>`).join(''); sel.value=blocos.includes(v)?v:'';}); renderPortariaMoradorSelect();}
function renderPortariaMoradorSelect(){const cond=portariaMsgCond.value||state.portariaUser?.condominio_id, bloco=portariaMsgBloco.value; const rows=state.moradores.filter(m=>(!cond||m.condominio_id===cond)&&(!bloco||moradorBlocoLabel(m)===bloco)); portariaMsgMorador.innerHTML='<option value="">Selecione o morador</option>'+rows.map(m=>`<option value="${m.id}">${esc(m.nome)} - Apto/Unidade: ${esc(m.apartamento||m.unidade||'-')} - CPF: ${esc(m.cpf||'')}</option>`).join('');}
function renderPortariaMoradores(){const cond=portariaFiltroCond.value||state.portariaUser?.condominio_id, bloco=portariaFiltroBloco.value, q=(portariaBusca.value||'').toLowerCase(); const rows=state.moradores.filter(m=>(!cond||m.condominio_id===cond)&&(!bloco||moradorBlocoLabel(m)===bloco)&&(!q||JSON.stringify(m).toLowerCase().includes(q))); portariaMoradoresList.innerHTML=table(['Nome','CPF','Torre/Bloco','Apartamento','Unidade','Condomínio','Vinculados'],rows.map(m=>[esc(m.nome),esc(m.cpf),esc(moradorBlocoLabel(m)),esc(m.apartamento||'-'),esc(m.unidade),condName(m.condominio_id),pessoasHtml(m)]));}
function renderPortariaConversas(){const p=state.portariaUser;if(!p)return; const msgs=state.mensagens.filter(m=>!isMsgDeletedForPortaria(m,p.id)&&(m.destinatario==='portaria'||m.remetente==='portaria')&&m.condominio_id===p.condominio_id); const adminMsgs=msgs.filter(m=>m.portaria_id===p.id&&(m.destinatario==='admin'||m.remetente==='admin')); if($('portariaAdminConversa')){const unreadAdmin=adminMsgs.filter(m=>m.destinatario==='portaria'&&!m.lida_portaria).length; $('portariaAdminConversa').innerHTML=`<div class="oc-card"><h3>Administração ${unreadAdmin?`<span class="notify-badge inline-badge">${unreadAdmin}</span>`:''}</h3><p class="hint">Conversa direta entre portaria e administração.</p><button class="mini-btn" onclick="abrirConversaPortariaAdmin()">Abrir conversa com administração</button></div>`;} const moradoresIds=[...new Set(msgs.map(m=>m.morador_id).filter(Boolean))]; const porBloco={}; moradoresIds.forEach(id=>{const mor=state.moradores.find(m=>m.id===id); if(!mor)return; const key=moradorBlocoLabel(mor); (porBloco[key]=porBloco[key]||[]).push(mor);}); portariaConversas.innerHTML=Object.entries(porBloco).sort(([a],[b])=>a.localeCompare(b,'pt-BR',{numeric:true})).map(([bloco,mors])=>`<details class="month-group" open><summary>${esc(bloco)} (${mors.length} conversa${mors.length>1?'s':''})</summary>${mors.map(mor=>{const conv=msgs.filter(m=>m.morador_id===mor.id); const unread=conv.filter(m=>m.destinatario==='portaria'&&!m.lida_portaria).length; return `<button class="mini-btn conv-btn" onclick="abrirConversaPortaria('${mor.id}')"><strong>${esc(mor.nome)}</strong>${unread?` <span class="notify-badge inline-badge">${unread}</span>`:''}<br><small>Apto/Unidade: ${esc(mor.apartamento||mor.unidade||'-')} · CPF: ${esc(mor.cpf||'-')}</small></button>`}).join('')}</details>`).join('')||'<p>Nenhuma mensagem de moradores recebida.</p>';}
window.abrirConversaPortaria=(moradorId)=>{const mor=state.moradores.find(m=>m.id===moradorId); if(!mor)return; const msgs=state.mensagens.filter(m=>!isMsgDeletedForPortaria(m,state.portariaUser.id)&&m.morador_id===moradorId&&(m.destinatario==='portaria'||m.remetente==='portaria')).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)); msgs.forEach(m=>{if(m.destinatario==='portaria')m.lida_portaria=true}); saveRead(); renderBadges(); renderPortariaConversas(); portariaConversaAberta.innerHTML=`<div class="oc-card"><h3>${esc(mor.nome)} · ${esc(moradorBlocoLabel(mor))} · Apto ${esc(mor.apartamento||mor.unidade||'-')}</h3><div>${msgs.map(messageHtml).join('')||'<p>Sem mensagens.</p>'}</div><div class="form-grid one"><textarea id="portariaReplyText" placeholder="Responder mensagem"></textarea><label class="file-field">Imagem opcional<input id="portariaReplyImg" type="file" accept="image/*"></label><button class="btn btn-primary" type="button" onclick="enviarRespostaPortaria('${mor.id}')">Responder morador</button></div></div>`;}
window.enviarRespostaPortaria=async (moradorId)=>{const mor=state.moradores.find(m=>m.id===moradorId); const txt=$('portariaReplyText')?.value?.trim(); if(!mor||!txt)return toast('Digite a resposta.'); await sendMsg({texto:txt,img:await fileToData($('portariaReplyImg')?.files?.[0]),remetente:'portaria',destinatario:'morador',morador_id:mor.id,portaria_id:state.portariaUser.id,condominio_id:mor.condominio_id}); abrirConversaPortaria(mor.id); toast('Resposta enviada ao morador.');}
window.abrirConversaPortariaAdmin=()=>{const p=state.portariaUser;if(!p)return; const msgs=state.mensagens.filter(m=>!isMsgDeletedForPortaria(m,p.id)&&m.portaria_id===p.id&&(m.destinatario==='admin'||m.remetente==='admin')).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)); msgs.forEach(m=>{if(m.destinatario==='portaria')m.lida_portaria=true}); saveRead(); renderBadges(); if($('portariaConversaAberta')) $('portariaConversaAberta').innerHTML=`<div class="oc-card"><h3>Conversa com administração</h3><div>${msgs.map(messageHtml).join('')||'<p>Sem mensagens com a administração.</p>'}</div></div>`; renderPortariaConversas();}
if($('portariaAdminMsgForm')) portariaAdminMsgForm.onsubmit=async e=>{e.preventDefault(); const txt=portariaAdminMsgTexto.value.trim(); if(!txt)return toast('Digite a mensagem.'); await sendMsg({texto:txt,img:await fileToData(portariaAdminMsgImg.files[0]),remetente:'portaria',destinatario:'admin',portaria_id:state.portariaUser.id,condominio_id:state.portariaUser.condominio_id}); e.target.reset(); abrirConversaPortariaAdmin(); toast('Mensagem enviada para a administração.');}
portariaFiltroCond.onchange=()=>{renderPortariaUnidades();renderPortariaMoradores()}; portariaFiltroBloco.onchange=renderPortariaMoradores; portariaBusca.oninput=renderPortariaMoradores; portariaMsgCond.onchange=renderPortariaUnidades; portariaMsgBloco.onchange=renderPortariaMoradorSelect;
portariaMsgForm.onsubmit=async e=>{e.preventDefault(); const m=state.moradores.find(x=>x.id===portariaMsgMorador.value); if(!m)return; await sendMsg({texto:portariaMsgTexto.value,img:await fileToData(portariaMsgImg.files[0]),remetente:'portaria',destinatario:'morador',morador_id:m.id,portaria_id:state.portariaUser.id,condominio_id:m.condominio_id}); e.target.reset(); portariaMsgCond.value=state.portariaUser.condominio_id; renderPortariaUnidades(); toast('Mensagem enviada ao morador.');}
function saveRead(){ if(useSupabase){state.mensagens.forEach(m=>db.from('mensagens').update({lida_admin:m.lida_admin,lida_morador:m.lida_morador,lida_portaria:m.lida_portaria,deleted_by:m.deleted_by}).eq('id',m.id)); state.avisos.forEach(a=>db.from('avisos').update({lidos:a.lidos,ocultos:a.ocultos}).eq('id',a.id));} else {localSave('mensagens'); localSave('avisos');}}
window.markAvisoRead=id=>{const a=state.avisos.find(x=>x.id===id); if(a&&state.morador){const l=parseJson(a.lidos,[]); if(!l.includes(state.morador.id)){l.push(state.morador.id); a.lidos=JSON.stringify(l); saveRead(); renderBadges();}}}
function renderBadges(){setBadge('badgeAdminMsgs',state.mensagens.filter(m=>m.destinatario==='admin'&&!m.lida_admin).length); setBadge('badgeAdminPortaria',state.mensagens.filter(m=>m.remetente==='portaria'&&m.destinatario==='admin'&&!m.lida_admin).length); if(state.morador){const mid=state.morador.id; setBadge('badgeMoradorAvisos',state.avisos.filter(a=>a.condominio_id===state.morador.condominio_id&&!isHiddenForMorador(a,mid)&&!parseJson(a.lidos,[]).includes(mid)).length); setBadge('badgeMoradorAdmin',state.mensagens.filter(m=>m.morador_id===mid&&!isMsgDeletedForMorador(m,mid)&&m.destinatario==='morador'&&m.remetente==='admin'&&!m.lida_morador).length); setBadge('badgeMoradorPortaria',state.mensagens.filter(m=>m.morador_id===mid&&!isMsgDeletedForMorador(m,mid)&&m.destinatario==='morador'&&m.remetente==='portaria'&&!m.lida_morador).length);} if(state.portariaUser){const pid=state.portariaUser.id; setBadge('badgePortariaMsgs',state.mensagens.filter(m=>m.condominio_id===state.portariaUser.condominio_id&&!isMsgDeletedForPortaria(m,pid)&&m.destinatario==='portaria'&&!m.lida_portaria).length);}}
function hideModal(){modal.classList.add('hidden'); modalBody.innerHTML=''} window.hideModal=hideModal; modalClose.onclick=hideModal;
function showModal(html){modalBody.innerHTML=html; modal.classList.remove('hidden')}
window.showPlate=id=>{const m=state.moradores.find(x=>x.id===id); const img=m?.foto_placa_data||m?.foto_placa_url; if(img)showModal(`<h3>Placa do veículo</h3><img src="${img}" class="modal-img">`)};
window.showPessoas=id=>{const m=state.moradores.find(x=>x.id===id); const ps=parseJson(m?.pessoas_vinculadas,[]); showModal(`<h3>Pessoas vinculadas a ${esc(m?.nome)}</h3>`+table(['Nome','CPF'],ps.map(p=>[esc(p.nome),esc(p.cpf)])))};
function openEditModal(m){showModal(`<h3>Editar morador</h3><p>O cadastro foi carregado no formulário. Acrescente ou remova informações e clique em <b>Atualizar cadastro do morador</b>.</p><div class="info-grid"><span>Nome: ${esc(m.nome)}</span><span>CPF: ${esc(m.cpf)}</span><span>Unidade: ${esc(m.unidade)}</span><span>Placa: ${esc(m.placa_veiculo)}</span></div>`)}
window.showImages=(id,keep=false)=>{const l=state.lancamentos.find(x=>x.id===id), imgs=parseJson(l?.imagens,[]); if(!imgs.length)return toast('Nenhuma imagem anexada.'); if(!keep) state.slide=0; showModal(`<h3>${esc(l.titulo)} - imagens</h3><div class="slide-box"><button class="mini-btn slide-arrow" onclick="prevSlide('${id}')">‹</button><img src="${imgs[state.slide]?.data}" class="modal-img"><button class="mini-btn slide-arrow" onclick="nextSlide('${id}')">›</button></div><small>${state.slide+1} de ${imgs.length}</small>`)}
window.prevSlide=id=>{const imgs=parseJson(state.lancamentos.find(x=>x.id===id)?.imagens,[]); state.slide=(state.slide-1+imgs.length)%imgs.length; showImages(id,true)}; window.nextSlide=id=>{const imgs=parseJson(state.lancamentos.find(x=>x.id===id)?.imagens,[]); state.slide=(state.slide+1)%imgs.length; showImages(id,true)};
window.showDocs=(id,keep=false)=>{const l=state.lancamentos.find(x=>x.id===id), docs=parseJson(l?.documentos,[]); if(!docs.length)return toast('Nenhum documento anexado.'); if(!keep) state.docSlide=0; const d=docs[state.docSlide]; showModal(`<h3>${esc(l.titulo)} - documentos</h3><div class="slide-box"><button class="mini-btn slide-arrow" onclick="prevDoc('${id}')">‹</button><iframe class="pdf-frame" src="${d.data}"></iframe><button class="mini-btn slide-arrow" onclick="nextDoc('${id}')">›</button></div><small>Documento ${state.docSlide+1} de ${docs.length}: ${esc(d.name)}</small>`)}
window.prevDoc=id=>{const docs=parseJson(state.lancamentos.find(x=>x.id===id)?.documentos,[]); state.docSlide=(state.docSlide-1+docs.length)%docs.length; showDocs(id,true)}; window.nextDoc=id=>{const docs=parseJson(state.lancamentos.find(x=>x.id===id)?.documentos,[]); state.docSlide=(state.docSlide+1)%docs.length; showDocs(id,true)};
function avisoImages(a){const imgs=parseJson(a?.imagens,[]); if(imgs.length)return imgs; return a?.imagem?[{name:'imagem-aviso',type:'image/*',data:a.imagem}]:[]}
window.showAvisoImages=(id,keep=false)=>{const a=state.avisos.find(x=>x.id===id), imgs=avisoImages(a); if(!imgs.length)return toast('Nenhuma imagem no aviso.'); if(!keep)state.noticeSlide=0; markAvisoRead(id); showModal(`<h3>${esc(a.titulo)} - imagens do aviso</h3><div class="slide-box"><button class="mini-btn slide-arrow" onclick="prevAvisoImg('${id}')">‹</button><img src="${imgs[state.noticeSlide]?.data}" class="modal-img"><button class="mini-btn slide-arrow" onclick="nextAvisoImg('${id}')">›</button></div><small>${state.noticeSlide+1} de ${imgs.length} · Postado em ${new Date(a.created_at||Date.now()).toLocaleString('pt-BR')}</small>`)};
window.prevAvisoImg=id=>{const imgs=avisoImages(state.avisos.find(x=>x.id===id)); state.noticeSlide=(state.noticeSlide-1+imgs.length)%imgs.length; showAvisoImages(id,true)}; window.nextAvisoImg=id=>{const imgs=avisoImages(state.avisos.find(x=>x.id===id)); state.noticeSlide=(state.noticeSlide+1)%imgs.length; showAvisoImages(id,true)};
window.ocultarAvisoMorador=id=>{const a=state.avisos.find(x=>x.id===id); if(!a||!state.morador)return; const ocultos=parseJson(a.ocultos,[]); if(!ocultos.includes(state.morador.id))ocultos.push(state.morador.id); a.ocultos=JSON.stringify(ocultos); saveRead(); renderMoradorAvisos(); renderBadges(); toast('Aviso removido do seu painel.')}
window.deleteMsgForMorador=id=>{const m=state.mensagens.find(x=>x.id===id); if(!m||!state.morador)return; const list=parseJson(m.deleted_by,[]); const key='morador:'+state.morador.id; if(!list.includes(key))list.push(key); m.deleted_by=JSON.stringify(list); saveRead(); renderMoradorMsgs(); renderBadges(); toast('Mensagem excluída do seu painel.')}
window.deleteMsgForPortaria=id=>{const m=state.mensagens.find(x=>x.id===id); if(!m||!state.portariaUser)return; const list=parseJson(m.deleted_by,[]); const key='portaria:'+state.portariaUser.id; if(!list.includes(key))list.push(key); m.deleted_by=JSON.stringify(list); saveRead(); renderPortariaConversas(); if($('portariaConversaAberta'))$('portariaConversaAberta').innerHTML=''; renderBadges(); toast('Mensagem excluída do painel da portaria.')}
document.querySelectorAll('.morador-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.morador-tabs button').forEach(x=>x.classList.toggle('active',x===b)); document.querySelectorAll('.morador-content').forEach(x=>x.classList.toggle('active',x.id==='mtab-'+b.dataset.mtab)); if(state.morador)renderMoradorMsgs(); renderBadges();});
document.querySelectorAll('.portaria-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.portaria-tabs button').forEach(x=>x.classList.toggle('active',x===b)); document.querySelectorAll('.portaria-content').forEach(x=>x.classList.toggle('active',x.id==='ptab-'+b.dataset.ptab)); if(state.portariaUser)renderPortariaConversas(); renderBadges();});

function csvSplitLine(line){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'&&line[i+1]==='"'){cur+='"';i++;continue}if(ch==='"'){q=!q;continue}if((ch===','||ch===';')&&!q){out.push(cur.trim());cur='';continue}cur+=ch}out.push(cur.trim());return out}
function parseCsvText(text){const lines=text.replace(/^\ufeff/,'').split(/\r?\n/).filter(l=>l.trim()); if(!lines.length)return []; const head=csvSplitLine(lines[0]).map(h=>h.trim().toLowerCase()); return lines.slice(1).map(line=>{const vals=csvSplitLine(line); return Object.fromEntries(head.map((h,i)=>[h,vals[i]||'']));});}
function csvVal(v){return `"${String(v??'').replaceAll("\r"," ").replaceAll("\n"," ").replaceAll('"','""')}"`}
baixarModeloMoradoresCsv.onclick=()=>{const head=['condominio_nome','nome','email','senha','cpf','celular','bloco','apartamento','unidade','placa_veiculo','pessoas_vinculadas']; const exemplo=['Condomínio Orquídea','Maria Silva','maria@email.com','123456','000.000.000-00','(92) 90000-0000','Torre 28','301','Torre 28 - 301','ABC1D23','João Silva - 111.111.111-11 | Ana Silva - 222.222.222-22']; const csv='sep=;\n'+[head.map(csvVal).join(';'), exemplo.map(csvVal).join(';')].join('\n'); download('modelo-cadastro-moradores.csv','\ufeff'+csv,'text/csv;charset=utf-8')};
importMoradoresCsv.onclick=()=>{const f=moradorCsvFile.files[0]; if(!f)return toast('Selecione o arquivo CSV.'); const r=new FileReader(); r.onload=async()=>{const rows=parseCsvText(r.result); let ok=0,fail=0; for(const row of rows){try{let cond=state.condominios.find(c=>(c.nome||'').toLowerCase()===(row.condominio_nome||'').toLowerCase()); if(!cond){cond={id:uid(),nome:row.condominio_nome||'Condomínio sem nome',endereco:'',responsavel:''}; await upsert('condominios',cond);} const bloco=row.bloco||''; const apartamento=row.apartamento||''; const unidade=row.unidade||[bloco,apartamento].filter(Boolean).join(' - '); const pessoas=(row.pessoas_vinculadas||'').split('|').map(x=>x.trim()).filter(Boolean).map(x=>{const [nome,...cpf]=x.split('-');return {nome:(nome||'').trim(),cpf:cpf.join('-').trim()}}); await upsert('moradores',{id:uid(),condominio_id:cond.id,nome:row.nome,email:row.email,senha:row.senha||'123456',cpf:row.cpf,celular:row.celular,bloco,apartamento,unidade,placa_veiculo:row.placa_veiculo,pessoas_vinculadas:JSON.stringify(pessoas)}); ok++;}catch(e){console.error(e);fail++;}} await loadAll(); toast(`Importação concluída: ${ok} moradores cadastrados${fail?`, ${fail} com erro`:''}.`); moradorCsvFile.value='';}; r.readAsText(f,'utf-8')};

function csvLine(values){return values.map(csvVal).join(';')}
function sortMoradoresForCsv(rows){return [...rows].sort((a,b)=>condName(a.condominio_id).localeCompare(condName(b.condominio_id),'pt-BR',{numeric:true})||moradorBlocoLabel(a).localeCompare(moradorBlocoLabel(b),'pt-BR',{numeric:true})||String(a.apartamento||'').localeCompare(String(b.apartamento||''),'pt-BR',{numeric:true})||String(a.nome||'').localeCompare(String(b.nome||''),'pt-BR'))}
function pessoasCsv(m){return parseJson(m.pessoas_vinculadas,[]).map(p=>`${p.nome||''} - ${p.cpf||''}`).join(' | ')}
exportCsv.onclick=()=>{const head=['Data','Título','Descrição','Categoria','Tipo','Valor','Condomínio']; const rows=state.lancamentos.map(l=>[l.data_lancamento,l.titulo,l.descricao||'',l.categoria,l.tipo,l.valor,condName(l.condominio_id)]); download('lancamentos-arquipelago.csv','\ufeffsep=;\n'+[csvLine(head),...rows.map(csvLine)].join('\n'),'text/csv;charset=utf-8')}
if($('exportMoradoresCsv')) $('exportMoradoresCsv').onclick=()=>{const head=['Condomínio','Torre/Bloco','Apartamento','Unidade','Nome','E-mail/Login','Senha','CPF','Celular','Placa do veículo','Pessoas vinculadas','ID do morador','ID do condomínio']; const rows=sortMoradoresForCsv(state.moradores).map(m=>[condName(m.condominio_id),moradorBlocoLabel(m),m.apartamento||'',m.unidade||'',m.nome||'',m.email||'',m.senha||'',m.cpf||'',m.celular||'',m.placa_veiculo||'',pessoasCsv(m),m.id||'',m.condominio_id||'']); download('moradores-arquipelago-organizado-por-torres.csv','\ufeffsep=;\n'+[csvLine(head),...rows.map(csvLine)].join('\n'),'text/csv;charset=utf-8')}
function buildBackup(){return {sistema:'Arquipelago Administracao de Condominios',versao_backup:'2.0',gerado_em:new Date().toISOString(),tables:Object.fromEntries(tables.map(t=>[t,state[t]||[]])),...Object.fromEntries(tables.map(t=>[t,state[t]||[]]))}}
exportJson.onclick=()=>download('backup-arquipelago-completo.json',JSON.stringify(buildBackup(),null,2),'application/json;charset=utf-8')
async function importBackupData(data){const src=data?.tables&&typeof data.tables==='object'?data.tables:data; const valid=tables.some(t=>Array.isArray(src?.[t])); if(!valid) throw new Error('Estrutura de backup não reconhecida.'); for(const t of tables){const rows=Array.isArray(src[t])?src[t]:[]; state[t]=rows.map(r=>({...r,id:r.id||uid()})); if(useSupabase&&rows.length){const payload=state[t].map(r=>({...r,updated_at:r.updated_at||new Date().toISOString()})); const {error}=await db.from(t).upsert(payload); if(error) throw error;} else localSave(t);} if(useSupabase) await loadAll(); else renderAll();}
importJson.onchange=e=>{const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=async()=>{try{const data=JSON.parse(r.result); await importBackupData(data); toast('Backup JSON importado com sucesso. Os dados foram carregados no sistema.')}catch(err){console.error(err); toast('Arquivo inválido ou incompatível com o backup do portal.')}}; r.readAsText(f,'utf-8'); e.target.value=''}
function download(name,content,type){const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([content],{type})); a.download=name; a.click(); URL.revokeObjectURL(a.href)}
removeMoradorBtn.onclick=()=>removeRow('moradores',removeMoradorSelect.value); removeLancamentoBtn.onclick=()=>removeRow('lancamentos',removeLancamentoSelect.value);
loadAll();
